tasks:
  - name: cdk
    before: |
      npm i -g aws-cdk

  - name: terraform
    before: |
      ./bin/terraform_cli_install.sh

  # random utilities
  - name: utils
    before: |
      sudo apt-get update
      sudo apt-get install -y tree unzip curl
  

  - name: install-deps
    init: |
      sudo apt-get update && sudo apt-get install -y jq


  # https://learn.microsoft.com/en-us/powershell/scripting/install/install-ubuntu?view=powershell-7.4
  # https://docs.aws.amazon.com/powershell/latest/userguide/pstools-getting-set-up-linux-mac.html
  # https://docs.aws.amazon.com/powershell/latest/reference/
  #- name: powershell
  #  before: |
  #    ./bin/powershell_cli_install.sh

  # https://docs.aws.amazon.com/cli/latest/userguide/getting-started-install.html

  - name: install-powershell
    before: |
      # Update package list
      sudo apt-get update

      # Install prerequisites
      sudo apt-get install -y wget apt-transport-https software-properties-common

      # Get Ubuntu version
      source /etc/os-release

      # Download the Microsoft repository keys
      wget -q https://packages.microsoft.com/config/ubuntu/$VERSION_ID/packages-microsoft-prod.deb

      # Register the Microsoft repository keys
      sudo dpkg -i packages-microsoft-prod.deb

      # Clean up
      rm packages-microsoft-prod.deb

      # Update package list after adding repo
      sudo apt-get update

      # Install PowerShell
      sudo apt-get install -y powershell
      

  - name: aws-cli
    env:
      AWS_CLI_AUTO_PROMPT: on-partial
    before: |
      curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "/tmp/awscliv2.zip"
      unzip -q /tmp/awscliv2.zip -d /tmp
      sudo /tmp/aws/install
      rm -rf /tmp/aws /tmp/awscliv2.zip
      aws --version