#!/usr/bin/env bash
echo "== deploy s3 bucket via CFN" #CFN= Cloud Formation

STACK_NAME="cfn-s3"
aws cloudformation deploy \
--template-file template.yaml \
--no-execute-changeset \
--region us-east-2 \
--stack-name $STACK_NAME

